# Generated by Django 3.1.5 on 2021-01-14 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('teacher', models.CharField(max_length=1000)),
                ('excerpt', models.TextField(max_length=3000)),
                ('description', models.TextField()),
                ('num_lessons', models.PositiveSmallIntegerField()),
                ('pictures', models.ImageField(upload_to='courses_pictures')),
            ],
        ),
    ]
